export const projects = [
  {
    slug: "thermal-atlas",
    name: "Thermal Atlas",
    year: "2026",
    status: "Active",
    type: "Motor Thermal Research / Model Gallery + Result Agent",
    summary:
      "面向 LPTN、TNN、STNN 与 DSTNN 的电机温度估计实验画廊。将模型拓扑、训练版本与测试结果组织成可拖拽 stamp，并把 evidence-grounded Agent 直接嵌入对比工作流。",
    tags: ["Result Agent", "Experiment Evidence", "Model Gallery", "Motor Thermal"],
    repo: "https://github.com/Vonct/motor_temp_estimation_avgTemp/tree/main/apps/thermal-model-gallery",
    demo: "",
    role: "独立设计与实现",
    duration: "Ongoing",
    theme: "thermal",
    gallery: [
      {
        src: "./imgs/thermal_atlas_editions.png",
        alt: "Thermal Atlas 中同一模型拓扑的不同训练与初始化 edition",
        label: "01 / MODEL EVIDENCE",
        caption: "具体拓扑与训练链路被组织成独立 stamp；用户可以把选定实验直接引用到 Agent。",
      },
      {
        src: "./imgs/thermal_atlas_agent.png",
        alt: "Thermal Atlas 内嵌 Result Agent 的 evidence tray 与引用式分析",
        label: "02 / EMBEDDED AGENT",
        caption: "Agent 与 Gallery 共用证据上下文，回答中的 S1、S2 可以回查到具体实验结果。",
      },
    ],
    metrics: [
      { value: "12", label: "model stamps" },
      { value: "48", label: "profiles indexed" },
      { value: "S1–S8", label: "frozen evidence" },
    ],
    stack: [
      "React 19 / TypeScript / Vite",
      "Tauri 2",
      "Node.js Agent Server",
      "OpenAI-compatible Chat Completions",
      "SSE Streaming",
      "SQLite",
      "Docker Compose (optional)",
    ],
    highlights: [
      "用 method、topology、state/boundary node 与 edition 组织可追溯模型档案",
      "通过拖拽 stamp 冻结单轮 evidence，量化结论以 S1–S8 回指源报告",
      "比较前检查 dataset、split、目标语义、初始化方式与测试 profile，避免错误排名",
      "Kimi 通过 OpenAI-compatible provider 接入，Gallery 在 Agent 离线时仍可独立使用",
    ],
    detailMd: "./content/projects/thermal-atlas.md",
  },
  {
    slug: "ourmemory",
    name: "TinyUniverse.ai",
    year: "2026",
    status: "Active",
    type: "WeChat Mini Program / AI Memory App",
    summary:
      "一个基于 AI 能力增强的微信回忆录小程序，围绕照片归档、空间化管理、城市识别、内容总结与视频生成，探索记忆内容的结构化整理与再表达。",
    tags: ["WeChat Mini Program", "AI Memory", "Cloud Functions", "AI Video"],
    repo: "https://github.com/Vonct/memories_miniprogram",
    demo: "",
    role: "独立设计与实现",
    duration: "Ongoing",
    stack: [
      "WeChat Mini Program",
      "Tencent CloudBase",
      "Node.js Cloud Functions",
      "MiniMax",
      "EXIF / Geo Parsing",
    ],
    highlights: [
      "围绕旅行、约会、日常、美食四类内容设计统一回忆录信息架构",
      "支持房间切换与邀请码加入，让内容管理从单相册扩展到空间化组织",
      "旅行照片自动解析 GPS / 城市信息，美食照片支持分类与评分标注",
      "接入AI视频生成与 Agent 总结能力，增强内容再表达",
    ],
    detailMd: "./content/projects/ourmemory.md",
  },
  {
    slug: "mylabagent",
    name: "myLabAgent",
    year: "2026",
    status: "Active",
    type: "Shared Agent Runtime / Lab Workflow",
    summary:
      "面向实验室工作效率提升与自动化工具链建设的共享 Agent runtime，支持 Web / CLI 双入口，统一承接检索、工具调用、会话与记忆管理，以及垂直功能自动化流程。",
    tags: ["Memory", "Shared Runtime", "Automation", "CLI", "Web"],
    repo: "https://github.com/Vonct/myLabAgent",
    demo: "",
    role: "独立设计与实现",
    duration: "Ongoing",
    featured: true,
    theme: "labagent",
    cover: "./imgs/labagent_boot.png",
    stack: [
      "Python",
      "Streamlit",
      "Rich",
      "Chroma",
      "Multi-model Adapter",
      "JSON Session Store",
    ],
    highlights: [
      "支持 Web 与 CLI 双入口，共享同一套 Agent runtime 与工具能力",
      "设计 transcript / task / memory 分层机制，按相关性注入记忆以支撑多轮任务",
      "统一封装 RAG 检索、工具调用、本地 skill 挂载与 sub-agent 能力",
      "落地 DDS-IDL等垂直自动化流程，面向实验室真实开发场景",
    ],
    detailMd: "./content/projects/mylabagent.md",
  },
  {
    slug: "formula-student-driverless",
    name: "无人驾驶方程式2021-2023",
    nameHtml: "无人驾驶方程式<br><span class=\"formula-year\">2021-2023</span>",
    year: "2021–2023",
    status: "Completed",
    type: "Formula Student Driverless / Control · Perception · Calibration",
    summary:
      "围绕无人驾驶方程式赛车完成控制与环境感知工程：赛道轮廓约束下的 MPCC、锥桶识别、轨迹跟踪调试，以及定圆标定与车检；道路可行驶区域识别作为本科毕业设计单列开展。",
    tags: ["MPCC", "Cone Detection", "Circle Calibration", "Undergraduate Thesis"],
    cardVisual: {
      src: "./imgs/formula-mpcc-contouring.png",
      alt: "赛道轮廓约束下的 MPCC 轨迹示意图",
      label: "MPCC / TRACK CONTOURING",
    },
    repo: "",
    demo: "",
    role: "控制、感知与实车调试",
    duration: "2021–2023",
    theme: "formula",
    gallery: [
      {
        src: "./imgs/formula-mpcc-contouring.png",
        alt: "赛道边界、中心线与两条 MPCC 候选轨迹示意图",
        label: "01 / MPCC CONTOURING",
        caption: "重绘的 MPCC 核心示意：在赛道边界内权衡轮廓误差、纵向进度与过弯线路。",
      },
      {
        src: "./imgs/formula-mpcc-cone-prediction.png",
        alt: "MPCC 仿真中实测与预测锥桶、赛道切线和车辆状态",
        label: "02 / MPCC SIMULATION",
        caption: "仿真中同时展示实测锥桶、预测锥桶、赛道切线与车辆状态，用于检查约束和预测的一致性。",
      },
    ],
    metrics: [
      { value: "MPCC", label: "track contouring" },
      { value: "3D", label: "cone detection" },
      { value: "B.Eng.", label: "drivable-area thesis" },
    ],
    stack: [
      "C++ / ROS",
      "CasADi / IPOPT",
      "FSSIM / Gazebo / RViz",
      "MATLAB / Simulink / CarSim",
      "LiDAR Point Cloud",
      "PointPillars / TensorRT",
    ],
    highlights: [
      "实现赛道轮廓约束下的 MPCC：车辆模型、预测域代价、速度/控制约束和道路边界在同一求解框架内运行",
      "使用 RK4 离散与 CasADi 非线性求解器搭建 C++ 仿真链路，并在 FSSIM 中检查过弯轨迹与边界约束",
      "完成锥桶检测、目标跟踪与颜色估计相关的工程化学习和系统集成，为赛道边界判断提供输入",
      "完成定圆标定、车检模式和轨迹跟踪调试；本科毕业设计额外开展激光雷达可行驶区域识别",
    ],
    detailMd: "./content/projects/formula-student-driverless.md",
  },
];
