export const projects = [
  {
    slug: "thermal-atlas",
    name: "Thermal Atlas",
    year: "2026",
    status: "Active",
    type: "Motor Thermal Research / Model Gallery + Result Agent",
    summary:
      "面向 LPTN、TNN、STNN 与 DSTNN 的电机温度估计实验画廊。将模型拓扑、训练版本与测试结果组织成可拖拽 stamp，并把 evidence-grounded Agent 直接嵌入对比工作流。",
    tags: ["Result Agent", "Experiment Evidence", "Model Gallery", "Motor Thermal"],
    repo: "https://github.com/Vonct/motor_temp_estimation_avgTemp/tree/main/apps/thermal-model-gallery",
    demo: "",
    role: "独立设计与实现",
    duration: "Ongoing",
    theme: "thermal",
    gallery: [
      {
        src: "./imgs/thermal_atlas_editions.png",
        alt: "Thermal Atlas 中同一模型拓扑的不同训练与初始化 edition",
        label: "01 / MODEL EVIDENCE",
        caption: "具体拓扑与训练链路被组织成独立 stamp；用户可以把选定实验直接引用到 Agent。",
      },
      {
        src: "./imgs/thermal_atlas_agent.png",
        alt: "Thermal Atlas 内嵌 Result Agent 的 evidence tray 与引用式分析",
        label: "02 / EMBEDDED AGENT",
        caption: "Agent 与 Gallery 共用证据上下文，回答中的 S1、S2 可以回查到具体实验结果。",
      },
    ],
    metrics: [
      { value: "12", label: "model stamps" },
      { value: "48", label: "profiles indexed" },
      { value: "S1–S8", label: "frozen evidence" },
    ],
    stack: [
      "React 19 / TypeScript / Vite",
      "Tauri 2",
      "Node.js Agent Server",
      "OpenAI-compatible Chat Completions",
      "SSE Streaming",
      "SQLite",
      "Docker Compose (optional)",
    ],
    highlights: [
      "用 method、topology、state/boundary node 与 edition 组织可追溯模型档案",
      "通过拖拽 stamp 冻结单轮 evidence，量化结论以 S1–S8 回指源报告",
      "比较前检查 dataset、split、目标语义、初始化方式与测试 profile，避免错误排名",
      "Kimi 通过 OpenAI-compatible provider 接入，Gallery 在 Agent 离线时仍可独立使用",
    ],
    detailMd: "./content/projects/thermal-atlas.md",
  },
  {
    slug: "ourmemory",
    name: "TinyUniverse.ai",
    year: "2026",
    status: "Active",
    type: "WeChat Mini Program / AI Memory App",
    summary:
      "一个基于 AI 能力增强的微信回忆录小程序，围绕照片归档、空间化管理、城市识别、内容总结与视频生成，探索记忆内容的结构化整理与再表达。",
    tags: ["WeChat Mini Program", "AI Memory", "Cloud Functions", "AI Video"],
    repo: "https://github.com/Vonct/memories_miniprogram",
    demo: "",
    role: "独立设计与实现",
    duration: "Ongoing",
    stack: [
      "WeChat Mini Program",
      "Tencent CloudBase",
      "Node.js Cloud Functions",
      "MiniMax",
      "EXIF / Geo Parsing",
    ],
    highlights: [
      "围绕旅行、约会、日常、美食四类内容设计统一回忆录信息架构",
      "支持房间切换与邀请码加入，让内容管理从单相册扩展到空间化组织",
      "旅行照片自动解析 GPS / 城市信息，美食照片支持分类与评分标注",
      "接入AI视频生成与 Agent 总结能力，增强内容再表达",
    ],
    detailMd: "./content/projects/ourmemory.md",
  },
  {
    slug: "mylabagent",
    name: "myLabAgent",
    year: "2026",
    status: "Active",
    type: "Shared Agent Runtime / Lab Workflow",
    summary:
      "面向实验室工作效率提升与自动化工具链建设的共享 Agent runtime，支持 Web / CLI 双入口，统一承接检索、工具调用、会话与记忆管理，以及垂直功能自动化流程。",
    tags: ["Memory", "Shared Runtime", "Automation", "CLI", "Web"],
    repo: "https://github.com/Vonct/myLabAgent",
    demo: "",
    role: "独立设计与实现",
    duration: "Ongoing",
    featured: true,
    theme: "labagent",
    cover: "./imgs/labagent_boot.png",
    stack: [
      "Python",
      "Streamlit",
      "Rich",
      "Chroma",
      "Multi-model Adapter",
      "JSON Session Store",
    ],
    highlights: [
      "支持 Web 与 CLI 双入口，共享同一套 Agent runtime 与工具能力",
      "设计 transcript / task / memory 分层机制，按相关性注入记忆以支撑多轮任务",
      "统一封装 RAG 检索、工具调用、本地 skill 挂载与 sub-agent 能力",
      "落地 DDS-IDL等垂直自动化流程，面向实验室真实开发场景",
    ],
    detailMd: "./content/projects/mylabagent.md",
  },
  {
    slug: "next-project",
    name: "Next Project",
    year: "TBD",
    status: "Coming Soon",
    type: "Future Work",
    summary:
      "待更新开发过的项目（TinyUiverse.ai[小程序回忆录], AI-Applications on TC4xx-PPU）",
    tags: ["Placeholder"],
    repo: "",
    demo: "",
    role: "待填写",
    duration: "TBD",
    stack: ["To be updated"],
    highlights: [
    ],
    detailMd: "./content/projects/next-project.md",
  },
];
